#!/bin/bash

#docker run -it golang:latest /bin/bash
docker run -it --network=devnet --volume="${PWD}/../docker-compose/core/dash.conf:/dash.conf" --volume="${PWD}:/proj" --volume=/var/run/docker.sock:/var/run/docker.sock golang:latest /bin/bash
